[package]
name = "art"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
gfx = "*"
gfx_device_gl = "*"
find_folder = "*"

systems =  { path="../systems" }
components = { path="../components" }
graphics = { path="../graphics" }
