[package]
name = "art"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
gfx = "*"
gfx_device_gl = "*"
find_folder = "*"
log = "*"
env_logger = "*"

graphics = { path="../graphics" }
utils = { path="../utils" }
