[package]
name = "explore"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
nalgebra = "*"

core = { path="src/core" }
art = { path="src/art" }
components = { path="src/components" }
math = { path="src/math" }
