[package]
name = "components"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
specs = "*"
nalgebra = "*"

graphics = { path="../graphics" }
utils = { path="../utils" }
math = { path="../math" }
